storage_sweep:
    #atm this is not used
    init_storage: 3
    # the other params come from floquet general experiment (will overwrite its params)
    start: 0.007 # 
    step: 100 # 
    qubits: [0]
    expts: 100 # 250
    reps: 200
    rounds: 1
    prepulse: True
    postpulse: True
    active_reset: False
    man_reset:  False
    storage_reset:  False

FloquetGeneralExperiment:
    init_storage: 4
    start: 0.007 # 
    step: 60 # 
    qubits: [0]
    expts: 100
    reps: 100
    rounds: 1
    flux_drive: ['low', 874, 9000, 0.05] # [low/high (ch), freq, gain, ramp_sigma(us)] RF flux modulation, gaussian flat top pulse
    prepulse: True
    postpulse: True
    active_reset: False
    man_reset:  False
    storage_reset:  False
    update_post_pulse_phase: [False, 1.07]

